[package]
authors = ["E <edgeworth.dev@gmail.com>"]
edition = "2018"
name = "memeroute"
version = "0.1.0"

[workspace]
members = ["memeroute-gui"]

[dependencies]
approx = "*"
auto_ops = "*"
derive_more = "*"
earcutr = "*"
eyre = "*"
nalgebra = "*"
ordered-float = "*"
parry2d-f64 = "*"
petgraph = "*"
priority-queue = "*"
regex = "*"
serde = {version = "*", features = ["derive"]}
strum = {version = "*", features = ["derive"]}

[dev-dependencies]
criterion = {version = "*", features = ["real_blackbox"]}

# Build dependencies with optimisations - debug builds will run faster
# but dependencies don't change often.
[profile.dev.package."*"]
opt-level = 3
