[package]
authors = ["E <edgeworth.dev@gmail.com>"]
edition = "2021"
name = "memeroute-gui"
version = "0.1.0"

[dependencies]
color-eyre = "*"
derive_more = "*"
eframe = {version = "*", features = ["persistence", "default_fonts"]}
eyre = "*"
lazy_static = "*"
log = "*"
memeroute = {version = "*", path = ".."}
num-traits = "*"
pretty_env_logger = "*"
serde = {version = "*", features = ["derive"]}
structopt = "*"
tokio = {version = "*", features = ["full"]}
